# Run the functions that we want
__mise_en_place
__install_brew_personal
__set_personal_wallpaper
__install_mas_personal
__install_pwa_personal
__install_ai_stack_personal
__take_care_of_general_stuff
__set_personal_dock
