# Run the functions that we want
__mise_en_place
__install_via_brew
__install_via_mas
__install_as_pwa
__general_uiux
__general_io
__energy
__screenshots
__more_ui
__finder
__safari
__textedit
__updates
__photos
__country_dock