#!/usr/bin/env zsh

echo "Customizing the Dock..."

# ✅ Remove all dock items
dockutil --remove all --no-restart

# ✅ Add links to desktop and Box
dockutil --add "/" --view grid --display folder --no-restart
dockutil --add "$HOME/Desktop" --view grid --display folder --no-restart

# ✅ Add back apps in the order we care about
dockutil --add /System/Applications/System\ Settings.app --no-restart
dockutil --add /System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app/ --no-restart
dockutil --add /System/Applications/Messages.app --no-restart
dockutil --add /Users/"$USER"/Applications/Gmail.app/
