#!/usr/bin/env zsh

echo "Checking if iCloud is signed in..."

# ✅ Check if iCloud is signed in and exit if it’s not
if defaults read MobileMeAccounts | grep -q AccountID; then
  echo "iCloud is signed in. Proceeding..."
  # Set variable to indicate icloud is signed in
  ICLOUD_IS_SIGNED_IN=0
else
  echo "iCloud is not signed in. Some parts of the scripts will not be completed."
  # Set variable to indicate icloud is signed in
  # shellcheck disable=SC2034
  ICLOUD_IS_SIGNED_IN=1

fi