#!/usr/bin/env zsh

echo "Checking if System Preferences is closed..."

# ✅ Prevent them from overriding settings we’re about to change
usr/bin/osascript -e 'tell application "System Preferences" to quit'
