#!/usr/bin/env zsh

heading "Installing web apps..."

# ✅ Function to make a PWA
function __make_pwa {
  /usr/bin/osascript <<EOF
  tell application "Safari"
    activate
    open location "$1" -- The URL of the website you want to make a PWA of
  end tell
EOF

  # Wait for user to press enter
  echo "Press [Enter] to continue once you have logged in..."
  read -r

  /usr/bin/osascript <<EOF
  tell application "Safari"
    activate
  end tell
  tell application "System Events"
    tell process "Safari"
      click menu bar item "File" of menu bar 1 -- Open the "File" menu
      delay 0.5 -- Allow the menu to appear

      -- Select "Add to Dock…" menu item
      click menu item "Add to Dock…" of menu 1 of menu bar item "File" of menu bar 1

      -- Hit "Enter" to confirm in case a modal dialog appears
      delay 1.0 -- Allow time for the modal to appear and for the thumbnail to load
      keystroke return -- Hit "Enter" to confirm
    end tell
  end tell
EOF
}

# Wait for user to press enter
echo  "For each PWA, ensure that the webpage is logged in. Then press [Enter] to continue. If you are ready, press [Enter] now."
read -r

# ✅ Install a GMail PWA
__make_pwa "https://mail.google.com/mail/u/0/#inbox"
