#!/usr/bin/env zsh

# Check if variable IS_ICLOUD_SIGNED_IN is true
if [[ $IS_ICLOUD_SIGNED_IN == false ]]; then
  echo "iCloud is not signed in. Skipping App Store installations."
else
  echo "Installing fun applications..."
fi
