#!/usr/bin/env zsh

# Check if variable IS_ICLOUD_SIGNED_IN is true
if [[ $IS_ICLOUD_SIGNED_IN == 1 ]]; then
  echo "iCloud is not signed in. Skipping App Store installations."
else

  # ✅ Install developer tools
  mas install 497799835 # Xcode

  # ✅ Install collaboration tools
  mas install 803453959 # Slack
fi
