#!/usr/bin/env zsh

echo "Installing base applications with the App Store..."

# ✅ Install collaboration tools
mas install 310633997 # WhatsApp

# ✅ Install utilities
mas install 937984704 # Amphetamine

# ✅ Install document editing tools
mas install 462054704 # Microsoft Word
mas install 462058435 # Microsoft Excel
mas install 462062816 # Microsoft PowerPoint
