#!/usr/bin/env zsh

heading "Installing applications with Homebrew..."

# ✅ Install installation and configuration utilities
brew install mas dockutil

# ✅ Install utilities
brew install coreutils wget tree htop trash
