#!/usr/bin/env zsh

heading "Installing Homebrew..."

# ✅ Install Homebrew
yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# ✅ Add Homebrew to Path
echo >>/Users/"$USER"/.zprofile
echo "eval '$(/opt/homebrew/bin/brew shellenv)'" >>/Users/work/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

# ✅ Update Homebrew
brew update
brew upgrade
