#!/usr/bin/env zsh

# ✅ Install a few of my favorite local LLMs
download_jan_model "bartowski" "Qwen2.5-7B-Instruct-GGUF" "Qwen2.5-7B-Instruct-Q4_K_M.gguf"
download_jan_model "bartowski" "Qwen2.5-Coder-7B-Instruct-GGUF" "Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf"
download_jan_model "bartowski" "Qwen2-VL-7B-Instruct-GGUF" "Qwen2-VL-7B-Instruct-Q4_K_M.gguf"