#!/usr/bin/env zsh


# ✅ Install a few of my favorite local LLMs
download_llamacpp_model "bartowski" "Qwen2.5-0.5B-Instruct-GGUF" "Qwen2.5-0.5B-Instruct-Q4_K_M.gguf"
download_llamacpp_model "bartowski" "Qwen2.5-1.5B-Instruct-GGUF" "Qwen2.5-1.5B-Instruct-Q4_K_M.gguf"
download_llamacpp_model "bartowski" "Qwen2.5-3B-Instruct-GGUF" "Qwen2.5-3B-Instruct-Q4_K_M.gguf"
download_llamacpp_model "bartowski" "Qwen2.5-7B-Instruct-GGUF" "Qwen2.5-7B-Instruct-Q4_K_M.gguf"