name: play.zsh

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/workflows/test-work.yml"
      - ".github/workflows/static.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Make play.zsh
      run: sh build.sh
    - name: Run play.zsh script
      run: zsh scripts/play.zsh